# Generated by Django 3.0.5 on 2020-04-29 02:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户评论管理',
                'verbose_name_plural': '用户评论管理',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='部门名称')),
                ('introduce', models.TextField(verbose_name='部门介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '部门展示管理',
                'verbose_name_plural': '部门展示管理',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='历史名称')),
                ('year', models.CharField(max_length=30, verbose_name='历史年份')),
                ('detail', models.TextField(verbose_name='历史内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '历史展示管理',
                'verbose_name_plural': '历史展示管理',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='成员名称')),
                ('img', models.ImageField(default='default.jpg', upload_to=api.models.upload_to, verbose_name='成员图片')),
                ('grade', models.CharField(max_length=30, verbose_name='成员年级')),
                ('department', models.CharField(max_length=30, verbose_name='所属部门')),
                ('quotes', models.TextField(verbose_name='成员名言')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '成员展示管理',
                'verbose_name_plural': '成员展示管理',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='学生姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('phone', models.CharField(max_length=30, verbose_name='手机号码')),
                ('major', models.CharField(max_length=30, verbose_name='年级专业')),
                ('departer', models.CharField(max_length=30, verbose_name='选择部门')),
                ('status', models.IntegerField(verbose_name='目前阶段')),
                ('enable', models.BooleanField(verbose_name='激活状态')),
                ('sid', models.CharField(max_length=30, verbose_name='激活信息码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '注册信息管理',
                'verbose_name_plural': '注册信息管理',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='作品标题')),
                ('img', models.ImageField(default='default.jpg', upload_to=api.models.upload_to, verbose_name='作品封面')),
                ('year', models.CharField(blank=True, max_length=30, verbose_name='作品年份')),
                ('url', models.TextField(verbose_name='作品链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作品展示管理',
                'verbose_name_plural': '作品展示管理',
            },
        ),
    ]
